import { Vineyard, Restaurant, PlanOption } from './types';

export const planOptions: PlanOption[] = [
  {
    id: 'free',
    name: 'Basic',
    price: 0,
    duration: '1 Day',
    features: {
      vineyardSelection: '4',
      lunchSuggestion: '-',
      dinnerSuggestion: '-',
      mapView: true,
      liveAvailability: true,
      planSaved: '1 Day',
      pdfDownload: false,
      curatedOffers: false,
      premiumOffers: false,
      wineHotelBnB: '-',
      wineRatings: '-',
      aiAccess: '25€',
      accessToQA: false,
      savedSelections: '4',
      qualityRatings: true,
      planDownload: '-',
    },
  },
  {
    id: 'plus',
    name: 'Plus',
    price: 25,
    duration: '1 Week',
    features: {
      vineyardSelection: '6',
      lunchSuggestion: '-',
      dinnerSuggestion: '-',
      mapView: true,
      liveAvailability: true,
      planSaved: '1 Week',
      pdfDownload: false,
      curatedOffers: false,
      premiumOffers: false,
      wineHotelBnB: '-',
      wineRatings: '-',
      aiAccess: '25€',
      accessToQA: false,
      savedSelections: '6',
      qualityRatings: true,
      planDownload: 'email',
    },
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 50,
    duration: '4 Weeks',
    popular: true,
    features: {
      vineyardSelection: '11',
      lunchSuggestion: '3',
      dinnerSuggestion: '3',
      mapView: true,
      liveAvailability: true,
      planSaved: '4 Weeks',
      pdfDownload: false,
      curatedOffers: true,
      premiumOffers: false,
      wineHotelBnB: '3',
      wineRatings: 'Yes',
      aiAccess: '50€',
      accessToQA: false,
      savedSelections: '11',
      qualityRatings: true,
      planDownload: 'email',
    },
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 150,
    duration: '8 Weeks',
    features: {
      vineyardSelection: '17',
      lunchSuggestion: 'Yes',
      dinnerSuggestion: '5',
      mapView: true,
      liveAvailability: true,
      planSaved: '8 Weeks',
      pdfDownload: true,
      curatedOffers: true,
      premiumOffers: true,
      wineHotelBnB: '5',
      wineRatings: 'Yes',
      aiAccess: 'Yes',
      accessToQA: true,
      savedSelections: '17',
      qualityRatings: true,
      planDownload: 'email/pdf',
    },
  },
];

